name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    #- name: configure
      #run: chmod +x ./build_code.sh
    #- name: compile
      #run: ./build_code.sh
    - name: delete-old-file
      run: rm -rf *
    - name: copy-new-file
      run: cp -rf /home/master/honda/cicd/LT/* ./
    - name: compile
      run: python3 script/operation.py -m unit_test -t ubuntu -sudo hgtpass
